import React from 'react';
import Container from 'react-bootstrap/Container';

class TourEn extends React.Component {
    render() {
        return (
            <Container fluid>
                <h1>Kleistpark tour:</h1>
                <div className="tour">
                    <p>Kleistpark is hard to beat in Berlin, when it comes to places with more history per m2. And we are talking Berlin here, a city that breathes history. It encompasses over 300 years of German history, architecture and literature. Heinrich von Kleist was born roughly 30 years after the most popular and overrated writer in German history: Johann Wolfgang von Goethe. Born into a wealthy family, healthy Goethe never suffered in his life and unfortunately this lack of depth mirrors in his novels which have been torturing high school graduates for centuries. He knew very well that Kleist was much better than him, which is why he never adopted him as a protegé, which he would if he would really been a lover of language and literature. What he wanted was to become the icon of German intellectuals and he excelled. Nobody knows Kleist today but 100 years after his tragic suicide this park honored this underrated brilliant and tortured soul.</p>
                    <p>And it is this park that oozes history. The government can decide to rebuild the Berlin palace on museums island all they want, yet all they ever going to achieve is a simulacrum à la Disneyland but if you want to see the original leftovers from Frederik`s palace you can still see colonnades, which  were put here in the beginning of the 20th century. It is also one of the main hubs of one of the darkest chapters of German history: world war 2: Goebbels infamous sport-palace speech took place here. A few meters next to where Sport palace used to be, we will bump into the Kammergericht, highest state court for the city of Berlin. It was here that Freisler executed Stauffenberg and the members of the resistance group Die weiße Rose. But the notoriety of the courthouse goes back to the 18th century when the jurist ETA Hoffmann worked here while moonlighting as a writer of gothic horror and fantasy stories. Whilst barely known in Germany, let alone abroad he is said to be the biggest influence on none other than Edgar Allen Poe. Numerous sources have been researching this connection. Nowadays it is still in use today where it deals mainly with acts of terrorism.</p>
                    <p>I will also talk about the wild 70s with David Bowie and Iggy Pop living right next to the park. We will pass by his former apartment where he produced three of his most defining albums. In order to get there we will walk along Potsdamer straße, a street known to million of readers all around the globe. It was here that Christiane F. in “Wir Kinder vom Bahnhof Zoo” (We children from Zoo station) sold her body at the tender age of 13 in order to finance her heroine habit. The book, a huge success which spent weeks on the Spiegel bestseller list which is basically the German equivalent to the NYT bestseller list was translated into 18 languages. We can put off Wir Kinder vom Bahnhof Zoo as a piece of trashy social porn, that mythologizes and therefore almost idealizes the Berlin underground in the 70s, its outcasts, their hedonistic lifestyle, those beautiful loosers perennially moving through time to the sound of glam rock and declare it as piece of pulp fiction that solely relies on shock value, in a way that even the most teenagey Comedian would not get away with anymore. But we can also see it as testimonial of the angsty generation, that lived in constant fear of a nuclear war waiting to happen. The Socioeconomic class that Christiane F hailed from,  made heroin their drug of choice because they preferred the mellow calm heroin offered, over alcohol and thus seemingly opposed them diametrically to their parents who beat them up in a drunken stupor. At least in theory. The irony that none of these generations come from a culture that gave them any tool to deal with the trauma of a postwar generation raises questions if that trauma was ever resolved in the following generations.</p>
                </div>
            </Container>
        )
    }
}

export default TourEn;